language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

# install c interface for python for libgit2
before_install:
  - sudo apt-get install cmake
  - pip install cffi
  - "./.travis.sh"

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
